export { isArray, isFunction, isPromise, isString } from '@vue/shared'

export * from './dedupeHead'
export * from './ensureLeadingSlash'
export * from './ensureEndingSlash'
export * from './formatDateString'
export * from './htmlEscape'
export * from './htmlUnescape'
export * from './isLinkExternal'
export * from './isLinkHttp'
export * from './isLinkMailto'
export * from './isLinkTel'
export * from './isPlainObject'
export * from './normalizePackageName'
export * from './removeEndingSlash'
export * from './removeLeadingSlash'
export * from './resolveHeadIdentifier'
export * from './resolveLocalePath'
export * from './resolveRoutePathFromUrl'
