const path = require('path')

module.exports = (options, context) => ({
  name: 'test',

  async ready () {
    context.writeTemp('my-temp', 'A temp file generated by vuepress-plugin-test.')
  },

  extendPageData ({ content }) {
    return {
      size: (content.length / 1024).toFixed(2) + 'kb'
    }
  },

  enhanceAppFiles: [
    path.resolve(__dirname, 'enhanceApp.js')
  ],

  chainWebpack (config) {
    console.log(config)
  }

})
