import { isArray } from '@vuepress/utils'
import { Options, OptionsNormalized } from './types'

export const normalizeOptionClientDynamicModules = (
  clientDynamicModules: Required<Options>['clientDynamicModules'],
  pluginName: string
): OptionsNormalized['clientDynamicModules'] => async (app) => {
  // resolve clientDynamicModules object
  const clientDynamicModulesValue = await clientDynamicModules(app)

  const generatedFiles = isArray(clientDynamicModulesValue)
    ? clientDynamicModulesValue
    : [clientDynamicModulesValue]

  // set aliases
  Promise.all(
    generatedFiles.map(async ({ content, filename, dirname }) => {
      await app.writeTemp(
        `${dirname}/${filename}`,
        `\
/**
 * Generated by "${pluginName}"
 */

${content}
`
      )
    })
  )
}
