import type { App } from '../types'
import { createAppPages } from './createAppPages'
import {
  prepareClientAppEnhances,
  prepareClientAppSetups,
  prepareLayoutComponents,
  preparePageComponents,
  preparePageData,
  prepareRoutes,
  prepareSiteData,
} from './prepare'

/**
 * Prepare files for development or build
 *
 * - page components
 * - routes
 * - site data
 * - other files that generated by plugins
 */
export const appPrepare = async (app: App): Promise<void> => {
  // create pages
  app.pages = await createAppPages(app)

  // TODO: additionalPages

  // generate page component file
  await preparePageComponents(app)

  // generate page data files
  await preparePageData(app)

  // generate layout components map file
  await prepareLayoutComponents(app)

  // generate routes file
  await prepareRoutes(app)

  // generate site data file
  await prepareSiteData(app)

  // generate client app setups file
  await prepareClientAppSetups(app)

  // generate client app enhances file
  await prepareClientAppEnhances(app)

  // TODO: globalUIComponents

  // plugin hook: onPrepared
  await app.pluginApi.hooks.onPrepared.process(app)
}
