import type { App } from '../types'
import {
  prepareClientAppEnhances,
  prepareClientAppSetups,
  prepareLayoutComponents,
  preparePageComponent,
  preparePageData,
  preparePagesComponent,
  preparePagesData,
  prepareRoutes,
  prepareSiteData,
} from './prepare'

/**
 * Prepare files for development or build
 *
 * - page components
 * - routes
 * - site data
 * - other files that generated by plugins
 */
export const appPrepare = async (app: App): Promise<void> => {
  // generate page component files
  for (const page of app.pages) {
    await preparePageComponent(app, page)
  }
  await preparePagesComponent(app)

  // generate page data files
  for (const page of app.pages) {
    await preparePageData(app, page)
  }
  await preparePagesData(app)

  // generate layout components map file
  await prepareLayoutComponents(app)

  // generate routes file
  await prepareRoutes(app)

  // generate site data file
  await prepareSiteData(app)

  // generate client app setups file
  await prepareClientAppSetups(app)

  // generate client app enhances file
  await prepareClientAppEnhances(app)

  // TODO: globalUIComponents

  // plugin hook: onPrepared
  await app.pluginApi.hooks.onPrepared.process(app)
}
