const Tapable = require('../core/Tapable')
const { writeTemp } = require('../../prepare/util')

module.exports = class DynamicClientCodeOption extends Tapable {
  async run () {
    let code = ''
    for (const item of this.items) {
      const { value: fn, name: pluginName } = item
      const res = await fn()
      code += `
/**
 * Generated by [vuepress-plugin-${pluginName}]"
 */
${res}\n\n
        `.trim()
    }
    await writeTemp('dynamicClientCode.js', code)
  }
}
