'use strict'

/**
 * Module dependencies.
 */

const AsyncOption = require('../abstract/AsyncOption')

/**
 * clientDynamicModules option.
 */

module.exports = class ClientDynamicModulesOption extends AsyncOption {
  async apply (ctx) {
    await super.asyncApply()

    for (const item of this.appliedItems) {
      let { value: modules } = item
      const { name: pluginName } = item

      if (!Array.isArray(modules)) {
        modules = [modules]
      }

      await Promise.all(modules.map(async ({ name, content, dirname = 'dynamic' }) => {
        await ctx.writeTemp(
          `${dirname}/${name}`,
          `
/**
 * Generated by "${pluginName}"
 */
${content}\n\n
        `.trim())
      }))
    }
  }
}
