const Option = require('../Option')
const { writeTemp } = require('../../prepare/util')

module.exports = class ClientDynamicModulesOption extends Option {
  async apply () {
    for (const item of this.items) {
      const { value: fn, name: pluginName } = item
      let modules = await fn()
      if (!Array.isArray(modules)) {
        modules = [modules]
      }
      for (const { name, content } of modules) {
        await writeTemp(
          `dynamic-modules/${name}`,
          `
/**
 * Generated by [vuepress-plugin-${pluginName}]"
 */
${content}\n\n
        `.trim())
      }
    }
  }
}
